[package]
name = "testsearch-core"
version = "0.1.0"
edition = "2021"

[dependencies]
color-eyre.workspace = true
ignore = "0.4.23"
serde = { version = "1.0.214", features = ["derive"] }
skim.workspace = true
serde_json.workspace = true
tree-sitter = "0.23.2"
tree-sitter-python = "0.23.2"
